apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  annotations:
    author: Maximilian Lamm <maximilianlamm.kontakt@outlook.de>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: fi-ml/ARGOCD
          imagePullPolicy: Always
          ports:
            - containerPort: 80
