apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  type: NodePort
  selector:
    app: angular-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
